# Generated by Django 2.2.7 on 2019-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_img', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('cat_id', models.IntegerField()),
                ('pro_img', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_create', models.DateField()),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        
    ]
